[package]
edition.workspace = true
name = "katana"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.katana-db]
git = "https://github.com/dojoengine/dojo.git"
tag = "v0.4.4"
